project_id = "itsjonazifiiikozengd"

[functions.alfie-generate]
verify_jwt = false

[functions.alfie-chat]
verify_jwt = false

[functions.alfie-generate-ai-image]
verify_jwt = false

[functions.canva-oauth]
verify_jwt = false

[functions.generate-alfie-variant]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.create-connect-account]
verify_jwt = false

[functions.create-connect-onboarding-link]
verify_jwt = false

[functions.create-connect-dashboard-link]
verify_jwt = false

[functions.process-affiliate-payout]
verify_jwt = false

[functions.sync-connect-account-status]
verify_jwt = false

[functions.scrape-canva]
verify_jwt = false

[functions.auto-scrape-canva-templates]
verify_jwt = false

[functions.purchase-credit-pack]
verify_jwt = false

[functions.verify-credit-purchase]
verify_jwt = false
